interface FoundationModelData {
  explanation: string;
}

export default function FoundationModelPanel({
  data,
}: {
  data: FoundationModelData | null;
}) {
  if (!data?.explanation) {
    return <div className="text-text-dim text-xs">No explanation</div>;
  }

  return (
    <div className="space-y-2">
      <div className="text-[9px] tracking-[0.2em] text-text-dim">
        LLM SYNERGY ANALYSIS
      </div>
      <div className="bg-panel-light rounded p-3 border border-border">
        <p className="text-[11px] font-mono text-white/80 leading-relaxed whitespace-pre-wrap">
          {data.explanation}
        </p>
      </div>
      <div className="text-[8px] text-text-dim tracking-wider">
        GENERATED BY DATABRICKS FOUNDATION MODEL API
      </div>
    </div>
  );
}
