[project]
name = "stuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mimesis>=15.0.0",
    "pandas>=2.0.0",
]

[tool.uv.workspace]
members = [
    "help",
]
